# -*- coding: utf-8 -*-
"""Tensorflow-Introduction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sus7_iZRl85460JvfrnZwLsXBFIWBiTf
"""

import tensorflow as tf
tf.__version__

"""#### Tensorflow :

* It made up of Tensors which are n dimensional arrays
* Tensors are generalisation of matrices and vectors to higher dimensions
* Tensorflow is made up of graphs and sessions
* Each tensor has a datatype and shape
* Tensors define partially defined computations which produces value later
* Builds a graph of different tensor objects
* Running different parts of the graph generates results
"""

print(tf.version)

"""#### Tensors:"""

s1 = tf.Variable("sample string", tf.string)
s2 = tf.Variable(123, tf.int64)
s3 = tf.Variable(32.56, tf.float64)

s1.shape

# Rank/Degree - No of dimensions involved in the tensor
tf.rank(s1)

tf.rank(s2)

var = tf.ones([1,2,3])
var

var = tf.reshape(3,-1)
var

"""### Types of Tensors:

* Variable
* Constant
* Placeholder
* SparseTensor

Except variable, all others are immutable
"""

var_2 = tf.zeros([4,4,4,4])
var_2

var_2.shape

tf.rank(var_2)

var_2 = tf.reshape(var_2, [64, -1])
var_2.shape

tf.rank(var_2)

var_2

